name = "Taylor"
uuid = "0d749214-bdee-449c-a2f9-b2fa4e49104e"
authors = ["Loredana Cirstea <loredana.cirstea@gmail.com>"]
repo = "https://github.com/loredanacirstea/taylor.jl.git"
version = "0.0.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FromFile = "ff7dd447-1dcb-4ce3-b8ac-22a812192de7"

[compat]
julia = "1.4"
DataStructures = "0.18"
FromFile = "0.1"
