name = "Taylor"
authors = ["Loredana Cirstea <loredana.cirstea@gmail.com>"]
version = "0.0.1"
uuid = "0d749214-bdee-449c-a2f9-b2fa4e49104e"

[deps]
FromFile = "ff7dd447-1dcb-4ce3-b8ac-22a812192de7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
